Repository udistrital/oikos_api, pull requests merged in 2019-11, with the labels that each got.

#13 Correr CI #26
  main.go
Labels: bug

#14 Se corrige Drone.yml #9
  .drone.yml
Labels: bug

#15 Se corrigen migraciones para despligue #9
  database/migrations/20191010_105308_crear_tabla_tipo_espacio_fisico.go
  database/migrations/20191010_105717_crear_tabla_espacio_fisico.go
  database/migrations/20191010_110122_crear_tabla_tipo_uso.go
  database/migrations/20191010_111252_crear_tabla_tipo_dependencia.go
Labels: bug

#16 Se corrigen archivos de migraciones #9
  database/migrations/20191105_155035_crear_schema_oikos.go
  database/migrations/20191105_155048_crear_tabla_tipo_espacio_fisico.go
  database/migrations/20191105_155057_crear_tabla_espacio_fisico.go
  database/migrations/20191105_155111_crear_tabla_tipo_uso.go
  database/migrations/20191105_155122_crear_tabla_tipo_uso_espacio_fisico.go
  database/migrations/20191105_155133_crear_tabla_espacio_fisico_padre.go
  database/migrations/20191105_155142_crear_tabla_tipo_dependencia.go
  database/migrations/20191105_155148_crear_tabla_dependencia.go
  database/migrations/20191105_155154_crear_tabla_dependencia_tipo_dependencia.go
  database/migrations/20191105_155202_crear_tabla_dependencia_padre.go
  database/migrations/20191105_155223_crear_tabla_asignacion_espacio_fisico_dependencia.go
  database/migrations/20191105_155230_crear_tabla_campo.go
  database/migrations/20191105_155239_crear_tabla_espacio_fisico_campo.go
Labels: bug

#17 Se corrigen archivos de migraciones #9
  database/migrations/20191105_155060_crear_tabla_espacio_fisico.go
Labels: bug

#19 Redesplegar #6
  conf/app.conf
Labels: bug

#20 Se corrige el entrypoint #6
  entrypoint.sh
Labels: bug

#21 Se ajusta servicio de espacios fisicos para listar por tipo de espaci…
  controllers/espacio_fisico.go
Labels: bug

#22 Dev to test
  .drone.yml
  main.go
Labels: bug

#24 Update README.md
  README.md
Labels: documentation

#25 Update .drone.yml
  .drone.yml
Labels: bug

#27 Se agregan servicios adicionales hechos en V1 a ruta V2
  controllers/dependencia_padre_v2.go
  controllers/dependencia_v2.go
  controllers/espacio_fisico_v2.go
  routers/commentsRouter_controllers.go
Labels: enhancement
